### ISSUE TITLE
Does this work on Ropsten?

### ISSUE THREAD

**Issue by farhankhwaja** [projectchicago/gastoken#5]
Hi,

wanted to know whether this works on ROPSTEN, as I am trying to integrate GST2 into my contract and it never works. I made a really simple contract where I call a function which does the mint, this worked as expected. I got x tokens minted. But, then ran a function FreeNCallX(), where i added some logic over going over a fixed sized array and doing some maths. But this function doesnt seem to work at all.

I implemented the GST2.sol contract on ROPSTEN and then started using it.

So i wanted to know does this even work and if, yes, how can I get it to work on ROPSTEN.

**Comment by kruligh** [comment]
Hi, 
as far as i know GST2 has to be deployed at fixed address. To achieve it you has to deploy it from fixed account and with fixed nonce. It possible to change this properties by change original GST2 implementation - childs contacts have fixed creator address and you can change it. 
You can read about this in GST2_ETH.sol function makeChild() code comments.

Instead of changing code to own properties I would prefer to deploy GST2 from 'magic' account. Private key to 'magic' account is stored test/test_GST2.py lines 115-125 (commit 81325843c710fbcf0d77ea5a5e8323d373b09f88) 

I suppose it's reason of 'not working'.

**Comment by lorenzb** [comment]
@kruligh's explanation is spot on. 
We will deploy GST & GST2 on ropsten and rinkeby so that people can play with them.

**Comment by lorenzb** [comment]
**Ropsten**

GST1: [`0x88d60255F917e3eb94eaE199d827DAd837fac4cB`](https://ropsten.etherscan.io/address/0x88d60255f917e3eb94eae199d827dad837fac4cb)
GST2: [`0x0000000000b3F879cb30FE243b4Dfee438691c04`](https://ropsten.etherscan.io/address/0x0000000000b3f879cb30fe243b4dfee438691c04)

**Rinkeby**

GST1: [`0x88d60255F917e3eb94eaE199d827DAd837fac4cB`](https://rinkeby.etherscan.io/address/0x88d60255f917e3eb94eae199d827dad837fac4cb)
GST2: [`0x0000000000b3F879cb30FE243b4Dfee438691c04`](https://rinkeby.etherscan.io/address/0x0000000000b3f879cb30fe243b4dfee438691c04)
**Kovan**

GST1: [`0x88d60255F917e3eb94eaE199d827DAd837fac4cB`](https://kovan.etherscan.io/address/0x88d60255f917e3eb94eae199d827dad837fac4cb)
GST2: [`0x0000000000170CcC93903185bE5A2094C870Df62`](https://kovan.etherscan.io/address/0x0000000000170ccc93903185be5a2094c870df62)

Have fun on the testnet. 😃

**Comment by farhankhwaja** [comment]
Thanks  everyone. I knew i was missing something, couldn't figure out what.
